### ISSUE TITLE
Mapbox search: Un-pin location if one exists when someone searches

### ISSUE THREAD

**Issue by ajlevitz** [azilc/polling-place-map#18]
Problem:
1. I've clicked somewhere on the map, but it doesn't look right
2. I notice the search box and use it
3. The map zooms to the new location based on search
4. I assume the results have changed
5. The results haven't changed, and so I incorrectly see polling place locations based on the original pin

Ideal solution:
* When someone submits a search, clear/remove/un-pin a location on the map if one is set

Possible solution:
* When someone submits a search, don't zoom just to the searched location -- have the zoom include the searched location AND the existing pins on the map, so people can at least see how far away the results are

DO NOT USE solution:
* Change the pinned location to be the search. The chances that where they've searched is far from where they are registered to vote is too high.

**Comment by elizzard** [comment]
@ajlevitz 
1. Just a reaction:
If I don't select anything, but just do a search - there are no polling place results.
This is interesting, because I expected the search to act as a pin and give me polling locations. In other words, I was expecting the search action to be equivalent to pinning.

But if that were the desired behavior, I would expect the DO NOT USE solution to be viable. So the search is there to assist with panning the map to the correct place, but not with getting polling places?  How can we communicate that so that the users would know that form the get-go and not be like me?

2. I personally like the second "Possible Solution" better, to show all the pins and not lose progress. Losing progress is frustrating. 

What do you think?

**Comment by rmx90210** [comment]
This is a tricky one 🙈  @elizzard I think you hit on something important which is that it's _kind of_ broken even if you're just going through the more typical flow of:

1. Search for a location
2. Expect results to be there but they aren't

If we can make that work better, I think we might solve the unhappy path you identified as well @ajlevitz.

What about something like:

1. You search for a location
2. The map zooms to the general area but doesn't drop a pin. Instead it instructs you somehow you have to...
3. Place a pin on the map
4. Intended flow ensues

We can keep Mapbox from dropping a pin by setting `marker: false` in the geocoder [options](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md#parameters).

The open question is—how do we nudge the user to place a pin after that? Maybe we float a text bubble over the map that says "We've tried to find that location. Next, click the map to see polling places." ? Or that text could go in the existing header for "You've selected [...]"? (The latter is probably easier.)

**Comment by rmx90210** [comment]
@ajlevitz @elizzard I took a pass at adding the help text after you use the search box. This ain't pretty but just as a POC:

![image](https://user-images.githubusercontent.com/1463553/97666402-96cfc400-1a4b-11eb-9994-c8e48548b18a.png)

Demo at:
https://5f9bac5f4b898591a1198c16--az-polling-place-map-ilc.netlify.app

The code is on a branch `add-geocoder-help-text`

Let me know you think something like this might work (and open to any and all style suggestions!)

**Comment by elizzard** [comment]
@rbrtmrtn I tried the demo, and I like the flow. Don't have any style points. 

One thing - do we care about accessibility? I know very little about UX in this respect. Also this may be beyond scope. But I just wonder - how do people interact with the map using only voice? (I saw people use siri that way, for instance)

**Comment by rmx90210** [comment]
Closed by 709e9343c988ad6093a438a3ccab0a057fcfdab2.

**Comment by rmx90210** [comment]
@elizzard sorry I didn't mean to close this without responding to your comment!

I think that's a great question re: how do people navigate this using their voice. I'm not super well-versed in accessibility either, so I don't have a great answer, but we may be somewhat at the mercy of the Mapbox geocoder there. I would think/hope their (pretty awesome) team considered that in building the geocoding plugin, but IMO it's still a good question to ask.

It would be great to include that in an accessibility/UX review maybe after Election Day, given how close we are 🙁  I hate that we have to descope that for now, but it may take some expertise that I'm not sure our team has currently. USDR should be able to help!

**Comment by elizzard** [comment]
@rbrtmrtn I have an incling that the search field on the map may actually be the accessibility feature. So that would be (speech-to-text) - find search box, enter location, the search drops pin at the search result.. That is obviously conflicting with the do-not-use solution though.  Yeah, a subject matter expert would be useful to consult later :)
